### ISSUE TITLE
facebookEmailSave

### ISSUE THREAD

**Issue by lisamcho** [wevote/WeVoteServer#101]
facebook email isn't included as part of the frontend authentication response. It's a separate request once user is authenticated via facebook. Once we receive this response we need a way to save it to the user's account in the backend. Propose new facebookEmailSave endpoint (like facebookPhotoSave)

**Comment by DaleMcGrew** [comment]
In order to prevent a proliferation of specialized voter-data-update endpoints, I am thinking about transforming this API endpoint:
https://api.wevoteusa.org/apis/v1/docs/voterPhotoSave/

to: voterUpdate
and include a variety of voter fields we will want to update. If you don't pass a variable for a field (or pass "False"), the field wouldn't update.

Any objections @lisamcho?

**Comment by lisamcho** [comment]
Sounds good, @DaleMcGrew

**Comment by DaleMcGrew** [comment]
Fixed and live @lisamcho
