### ISSUE TITLE
Suggest Voter Guides List: Multi-select form to change VoterGuidePossibility status

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#1062]
On the Suggested Voter Guides page: https://api.wevoteusa.org/vg/possibility_list/?google_civic_election_id=1000080
...we need a way to select multiple rows (with check boxes) and then perform one of the following actions "Mark as...":

- Endorsements Not Available Yet (field: cannot_find_endorsements)
- Capture Detailed Comments (field: capture_detailed_comments)
- Candidates/Measures Missing (field: candidates_missing_from_we_vote)
- Stop Reviewing (field: hide_from_active_review)
- Ignore this Website (field: ignore_this_source)

These are currently set on the page where you are editing each Suggested Voter Guide, like this one:
https://api.wevoteusa.org/vg/create/?voter_guide_possibility_id=1508
![Screen Shot 2019-08-01 at 8 55 38 AM](https://user-images.githubusercontent.com/7756031/62308422-29914580-b43a-11e9-9ae9-e1f8345bd2fb.png)
And the data is stored in `VoterGuidePossibility` in `WeVoteServer/voter_guide/models.py`

Before starting, review this "stack" to see how the url and view take in input:
`views_admin.voter_guide_possibility_list_view` in `WeVoteServer/voter_guide/urls.py`
`voter_guide_possibility_list_view` in `/WeVoteServer/voter_guide/views_admin.py`

You will need to add a form to this page:
WeVoteServer/templates/voter_guide/voter_guide_possibility_list.html
...and the checkboxes to this included template page:
WeVoteServer/templates/voter_guide/voter_guide_possibility_table.html

You will need to set up the following files to process the form:
`views_admin.voter_guide_possibility_list_process_view` in `WeVoteServer/voter_guide/urls.py`
`voter_guide_possibility_list_process_view` in `/WeVoteServer/voter_guide/views_admin.py`

After processing `voter_guide_possibility_list_process_view`, return the browser to `https://api.wevoteusa.org/vg/possibility_list/`:
`voter_guide_possibility_list_view` in `WeVoteServer/voter_guide/views_admin.py`using code like this: `return HttpResponseRedirect(reverse('voter_guide:voter_guide_possibility_list', args=()))`

For saving the change to the VoterGuidePossibility table, the pattern on lines 841-854 which uses `update_or_create_voter_guide_possibility` in this file `WeVoteServer/voter_guide/models.py` might be a good starting point in `WeVoteServer/voter_guide/views_admin.py`.

**Comment by irascible** [comment]
If I am understanding the above correctly, would there be a kind of UI 'asymmetry' here in that you could mark the selected rows on the list page, but the result of those markings would not be visible until you visited each individual page? 

The problem is that there is hardly room to add the state of all those 5 markings on the list page, (which is presumably one reason why the checkboxes are on the individual page in the first place). But what if we added a single column to the list page called something like "any markings?" which would have an 'x' if any of the 5 values for the individual voter guide possibility had been set?  Another version of this would be to display a string of 5 characters such as 'x _ x _ _' which would show all 5 values, interpreted in the same order in which the checkbox options are displayed.

**Comment by DaleMcGrew** [comment]
Hi @irascible. What I would suggest on the listing page https://api.wevoteusa.org/vg/possibility_list/?google_civic_election_id=1000080 is to add a checkbox to the far right of each row, and then at the top right above the table (and the new column of checkboxes) add a drop-down with the options: Endorsements Not Available Yet, Capture Detailed Comments, Candidates/Measures Missing, etc. and a "Mark as..." button that saves all of the rows with the checkbox checked to include that new setting. Feel free to Slack me if you would like to discuss on a screenshare.

**Comment by irascible** [comment]
@DaleMcGrew: Thank you for clarifying, and let me do the same. I was suggesting adding two columns not just one. The first additional column would be the checkbox that you describe above, to enable marking a set of rows. The second additional column would allow you, in an abbreviated fashion, to see the result of such a marking, because otherwise (I believe) that state would be invisible on the listing page.  How would you otherwise know that something had been marked without going to the individual page?

**Comment by irascible** [comment]
Oops, okay, i missed the "show endorsements not available", etc. sorting links at the top of the listing page.

**Comment by irascible** [comment]
Once you've selected and marked one (or more) of the items in the list (with, for example, 'Candidates/Measures Missing'), is it correct that the marked item(s) disappear from the list view, until you click the matching filter at the top (for example "Show 'Candidates/Measures Missing'") to view the item(s)?

Also, there are 5 filters listed at the top, I am wondering whether, for consistency:

- Show 'Archived' should be renamed to Show 'Stop reviewing'
- an additional Show 'Ignore this website' filter should be added

**Comment by DaleMcGrew** [comment]
Yes, the item would disappear from the current list.

Sure, you can update the filter labels and add a new filter listing.

**Comment by DaleMcGrew** [comment]
Verified!
