### ISSUE TITLE
Add Authentication for App/Facebook/Google+

### ISSUE THREAD

**Issue by pertrai1** [wevote/WeVoteServer#33]

**Comment by DaleMcGrew** [comment]
Hi Rob, please note that we got this working in https://github.com/wevoteeducation/WeVoteBase and I would like to move over the existing authentication changes we made before we push forward on this issue. Some of it is here: https://github.com/wevoteeducation/WeVoteBase/tree/143ae29214a5fea24567482186c26e7afaebbbf0/wevote_social

**Comment by pertrai1** [comment]
Ok, I will change this to you as the move is made over.

**Comment by DaleMcGrew** [comment]
A first version (Facebook, Twitter, Your own email) is working in the Admin area: http://localhost:8000/admin/ We need to get versions of Facebook/Twitter working that anyone can use -- right now only Dale can use it because of how the Twitter and Facebook test apps are set up. To use the email/password sign in you need to manually enter your email address into the voter table, and set the password from the command line.
