### ISSUE TITLE
When new Twitter profile and banner photos are retrieved, also update Voter Guide & Organization

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#379]
We cache a voter's photos in a Voter Guide, Organization, and Position. When new Twitter profile and banner photos are retrieved, we should update the photos in all of the cached locations in a refresh function. We have some refresh/migration routines that could be upgraded or used.

We have done some work on this, and started an audit here:
https://docs.google.com/document/d/1Lz-JQOBYAYB0em0MNw8gMMUv-5KMuwuJT4-IfXMcb0A/edit#heading=h.400eehwfn2sb

**Comment by SailingSteve** [comment]
Got this done for Organization in #377

**Comment by SailingSteve** [comment]
@DaleMcGrew  So from the previous PR, Organization gets its twitter info and we_vote_hosted_profile_image_url_... from twitteruser.
In voter_guide/models in update_or_create_organization_voter_guide_by_election_id you receive an organization_we_vote_id that has no column in twitteruser, and it pulls from organization (which now pulls from twitteruser).

Is this existing code good enough?  If so this issue is done.

**Comment by SailingSteve** [comment]
Done
