### ISSUE TITLE
Update README with Ansible instructions

### ISSUE THREAD

**Issue by mshmsh5000** [wevote/WeVoteServer#445]
We haven't supported native Windows development. Now that we have a working Ansible-Vagrant install, let's update the instructions so that Windows (and other) users have a path forward.

**Comment by DaleMcGrew** [comment]
Hi @mshmsh5000, I was also thinking we could update WeVoteServer/config/environment_variables-template.json to default to "localhost" (instead of "api.wevoteusa.org") settings to make it easier for new developers to get started. Would you mind updating that file to the settings that work with Ansible-Vagrant?

**Comment by mshmsh5000** [comment]
Sounds good. Should I also update `WEB_APP_ROOT_URL` to `localhost:3000`, which I believe is how most devs would be running it, or just `WE_VOTE_SERVER_ROOT_URL`?

**Comment by DaleMcGrew** [comment]
Yes, I think we can assume that anyone running WeVoteServer locally will also have a `localhost:3000` WebApp. Thank you!

**Comment by mshmsh5000** [comment]
@DaleMcGrew Addressed in #447
