### ISSUE TITLE
IMPORT_TO_BE_DETERMINED

### ISSUE THREAD

**Issue by NeiloDull** [wevote/WeVoteServer#521]
Imported candidate list for Virginia 94th district not being accepted. I added 94th District manually into 'Offices' when 'add new ballot' function could not find an office for that area. 

https://api.wevoteusa.org/import_export_batches/batch_action_list/?batch_header_id=51&kind_of_batch=CANDIDATE&google_civic_election_id=4269

**Comment by DaleMcGrew** [comment]
Hi Neil, I updated the live server with an error message we can see that the office is still missing:
https://api.wevoteusa.org/import_export_batches/batch_action_list/?batch_header_id=51&kind_of_batch=CANDIDATE&google_civic_election_id=4269

If you create an office for "Member House of Delegates 94th District" and update the import csv https://docs.google.com/spreadsheets/d/1V3lvY183GElFDiWzyo1sR3vPZb8JMDMBVsvparkTaSg/edit#gid=0  to use that office instead of "Member House of Delegates 94th District - District 94 - va", the candidate imports should work.

**Comment by NeiloDull** [comment]
Perfect. Done!
