### ISSUE TITLE
Create Twitter Feed analyzer of hashtags & tracked_words

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#586]
We are automating the process of linking organizations to issues. We are starting on this by implementing the following:

We bring in and store locally all tweets for each organization.
We capture all hashtags from all tweets from that organization.
We search specifically for words (or combination of words) used in their Tweets.

Full description:
https://docs.google.com/document/d/1LpRijA7ijR-VV7xfjhCfib12CIUz9tq_sA3igxRG1M4/edit

**Comment by DaleMcGrew** [comment]
Hi @eayoungs, this is the new issue I wanted to invite you to work on.

**Comment by eayoungs** [comment]
Thanks @DaleMcGrew I'm definitely interested.

**Comment by eayoungs** [comment]
Hey, I think we need to set up the celery process to start gather this data at regular intervals so that we have enough data to explore analysis techniques and catch data quality issues as they arise.

I know we talked about this but has anyone started on this? I did a quick search of the issues but didn't see anything, yet.

@abdulrahimq @DaleMcGrew

**Comment by DaleMcGrew** [comment]
I just created an issue for setting up celery: https://github.com/wevote/WeVoteServer/issues/667

**Comment by DaleMcGrew** [comment]
For the future, but closing now.
