### ISSUE TITLE
Change endpoints to accept we_vote_id

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#87]
These are the endpoints to update (please feel free to rearrange based on order of priority):
Priority 1
- [x] https://api.wevoteusa.org/apis/v1/docs/positionListForBallotItem/

Priority 2
- [x] https://api.wevoteusa.org/apis/v1/docs/positionSupportCountForBallotItem/
- [x] https://api.wevoteusa.org/apis/v1/docs/positionOpposeCountForBallotItem/
- [x] https://api.wevoteusa.org/apis/v1/docs/voterSupportingSave/
- [x] https://api.wevoteusa.org/apis/v1/docs/voterStopSupportingSave/
- [x] https://api.wevoteusa.org/apis/v1/docs/voterOpposingSave/
- [x] https://api.wevoteusa.org/apis/v1/docs/voterStopOpposingSave/
- [x] https://api.wevoteusa.org/apis/v1/docs/voterStarOnSave/
- [x] https://api.wevoteusa.org/apis/v1/docs/voterStarOffSave/
- [x] https://api.wevoteusa.org/apis/v1/docs/voterStarStatusRetrieve/

Priority 3
- [x] https://api.wevoteusa.org/apis/v1/docs/positionPublicSupportCountForBallotItem/
- [x] https://api.wevoteusa.org/apis/v1/docs/positionPublicOpposeCountForBallotItem/

**Comment by lisamcho** [comment]
Some of the endpoints also return we_vote_id and some don't. (i.e. positionSupportCountForBallotItem returns 
{
count: 0,
status: "SUCCESSFUL_RETRIEVE_OF_POSITIONS_FOLLOWED_RE_CANDIDATE",
success: true
}

voterPositionRetrieve returns a candidate_we_vote_id field but the value is "".

I think with @nf071590 's implementation of the loadEndpoint function which fires an action, when the App Dispatcher receives an action it will also need the we_vote_id so it knows what candidate/ballot_item/etc the response matches. So should we return the we_vote_id in the server responses as well?

What do you think? Before, the we_vote_id was being passed around in the callbacks, which I guess we could also pass through the loadEndpoint function and ajax calls, but it seems cleaner to do it via server responses.

**Comment by DaleMcGrew** [comment]
Yes, returning we_vote_id with these API calls makes sense to me. :+1: I will include that in my refactoring.

**Comment by lisamcho** [comment]
:+1:

**Comment by lisamcho** [comment]
Thanks @DaleMcGrew! positionListForBallotItem is working for me. Having some issues with others.

voterStarOnSave, voterStarOffSave and voterStarStatusRetrieve don't seem to accept we_vote_id for items of type OFFICE. 
It works for CANDIDATE, but I can't get it working for starring 'President' for example.
The field is there on the API, but if you don't fill in the ballot_item_id you get this error:

{
success: false,
status: "STAR_ON_OFFICE STAR_ITEM_NOT_FOUND-MISSING_VARIABLES",
ballot_item_id: 0,
ballot_item_we_vote_id: "wv02off1",
kind_of_ballot_item: "OFFICE"
}

**Comment by DaleMcGrew** [comment]
Thanks for the heads up @lisamcho I'll look into it on my commute to Code for SF. ;)

**Comment by DaleMcGrew** [comment]
Bug fixed and pushed to the live API server. Thank you again for being so clear in your bug report @lisamcho.

**Comment by lisamcho** [comment]
@DaleMcGrew  If you enjoyed the last, I've got another one for you. voterPositionRetrieve returns a valid candidate_we_vote_id in the response ONLY if the user has either supported or opposed the candidate. Otherwise it returns "". 
Also, it returns success = false.  What does that mean exactly? Clearly server returned a response status 200. Nick's refactored Store example just returns without doing anything if success is false. Should this be success= true? After all, we did successfully determine that the user hasn't supported or opposed the item. Otherwise we can change frontend logic.

is_oppose: false,
statement_html: "",
statement_text: "",
success: false,
voter_device_id: "LK2OemYfHEgQ3DOpjuZwSBMVb5V4sbRBPDecAf4nPS5bIczntdLknQGIbwxy6GdlYL35pYaQIBGDncD4gY0ZzE6F",
last_updated: "",
office_we_vote_id: "",
speaker_display_name: "",
more_info_url: "",
speaker_image_url_https: "",
position_we_vote_id: "",
is_support: false,
position_id: 0,
stance: "",
ballot_item_display_name: "",
status: "RETRIEVE_POSITION_NONE_FOUND",
measure_we_vote_id: "",
google_civic_election_id: "",
candidate_we_vote_id: "",
is_information_only: false
}

**Comment by DaleMcGrew** [comment]
@lisamcho I just noticed I never confirmed that this is fixed: "Return the we_vote_id even if status = 'RETRIEVE_POSITION_NONE_FOUND'" The we_vote_id is returned in both "ballot_item_we_vote_id" and "candidate_we_vote_id". Success is also returned as true.

**Comment by DaleMcGrew** [comment]
All API endpoints updated and on live API server. Ready for VerifyFix.

**Comment by lisamcho** [comment]
@DaleMcGrew Looks good to me! :+1:
