### ISSUE TITLE
Upgrade the kind of GeoIP database we use from Maxmind

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteServer#994]
Joe has an update script that requests the latest database from Maxmind. These are the instructions Maxmind gives for downloading their database updates:
https://dev.maxmind.com/geoip/geoipupdate/

The old version of the Maxmind database we were using has been discontinued:
https://support.maxmind.com/geolite-legacy-discontinuation-notice/

...this is what Maxmind support said (I'd prefer to upgrade to GeoIP2):
```We discontinued the GeoLite Legacy database formats at the beginning of the year. support.maxmind.comhttps://support.maxmind.com/geolite-legacy-discontinuation-notice/ so you could purchase a license for the GeoIP2 City database and we can add access to the GeoIP Legacy City database. You can update your integration to use the free GeoLite2 databases, or if you're not able to, we do still support the paid GeoIP Legacy database formats```

We will buy the GeoIP2 City database (we update it during months we need fresh data).

And:
```Okay, you can find our open-source GeoIP2 API packages for the binary .mmdb format at https://dev.maxmind.com/geoip/geoip2/downloadable/```

His script was referring to http://www.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz

We need to stop using "http://www.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz" from Maxmind, and start using GeoIP2:
https://www.maxmind.com/en/geoip2-databases

Our instructions show how to install the free version under "Set up GeoIP" may need to be updated too:
https://github.com/wevote/WeVoteServer/blob/develop/docs/README_API_INSTALL_SETUP_ENVIRONMENT.md

**Comment by SailingSteve** [comment]
This turned out to be very straightforward, I am going to test some more before checking in.

At some point after the README_API_INSTALL_SETUP_ENVIRONMENT.md instructions were written, someone source controlled the old style GeoIP database at `WeVoteServer/geoip/import_data` which made updating it an unnecessary task for new developers.

I will be adding the new style GeoIP2 database to git at `WeVoteServer/geoip2/city-db/GeoLite2-City.mmdb`.  Joe's shell script should be modified to overwrite the single file of the "Lite" version DB with the latest paid production version.  

As for the `docs/README_API_INSTALL_SETUP_ENVIRONMENT.md`  I removed any mention of GeoLite.  

It doesn't seem like we need to worry about the old `geoip-api-c` c program, since installing it is optional in the latest install instructions.  Also there is no need to have each new developer get the latest version of the `GeoLite2-City.mmdb`, the one that is in source control should be fine for testing, and can be updated for all developers via source control (if needed).  So this checkin will also remove all the instructions to install the `GeoLite2-City.mmdb`.

**Comment by DaleMcGrew** [comment]
Hi Steve, I'd like to bump the priority of this issue back up now that Joe shared some thoughts via Slack. We also have a partner organization that is trying to get ready for an election in 35 days, so we will need to get our GeoIP system working again ASAP. Thank you!

**Comment by DaleMcGrew** [comment]
Verified!
